PUBDEV-8937: fix sort OOM error on multi-node
h2oai/h2o-3 pull request #15570
Opened 2023-06-12 15:52 UTC by wendycwong

This PR fixes the issue in: https://h2oai.atlassian.net/browse/PUBDEV-8937

There are two things that can blow up the memory:
1. During the sort stage, one node will have to store the sorting cols and the absolute row number ordering after it has finished the sorting.
2. During the sorted frame generation process, one node will have to store batchsize * all columns in the frame.  

Hence, OOM can occur during either 1 or 2.  Hence, instead of fixing the batchsize, when the memory per node is small, we will try to reduce the batchsize to prevent OOM during 1 or 2.  When there is not enough memory in the nodes, instead of silently throwing an OOM in the java backend, we will throw an error to the clients and alert the users.

2023-06-27 07:45 UTC, tomasfryda requested changes
Mostly, it looks good but there is one `Log.info` that I don't like.

2023-06-27 16:43 UTC, wendycwong commented on h2o-core/src/main/java/water/rapids/RadixOrder.java
> +    Log.info("batchsize ", batchSize);
I changed the error message.  Basically, the error message will tell the user how much memory they need in order to perform the sorting/merging action.  I do not want to go into too much detail and bring up the batchSize.  It is dependent on the size of their dataset and the number of columns that they want to sort/merge.

2023-06-28 07:35 UTC, tomasfryda commented on h2o-core/src/main/java/water/rapids/RadixOrder.java
> +    Log.info("batchsize ", batchSize);
Sorry I wasn't clear, I meant the `Log.info("batchsize ", batchSize);` line. When we'll get some logs to debug the "batchsize xxx" doesn't seem that helpful to me as you'll have to know to what that refers to and possibly it's not that convenient to `grep 'batchsize' log` as the word is probably used often.

2023-06-28 21:22 UTC, wendycwong commented on h2o-core/src/main/java/water/rapids/RadixOrder.java
> +    Log.info("batchsize ", batchSize);
That one is actually for my own use.  I will remove it then.

2023-06-29 16:14 UTC, merged