GH-15679 GBM Feature interaction bug
h2oai/h2o-3 pull request #15689
Opened 2023-08-10 18:29 UTC by maurever

Fix GBM params when a model converges with fewer trees than are in params.

Closes #15679

2023-08-10 20:20 UTC, wendycwong requested changes
Veronika:  Can you change or add a test that uses the customer dataset that is included in the issue?

2023-08-11 19:14 UTC, maurever commented
> Veronika: Can you change or add a test that uses the customer dataset that is included in the issue?

@wendycwong, what is the reason for adding the dataset? I reproduced the bug with different data, but the issue was the same. So I decided not to add the new data. The data from Uri are also used just for testing, they are not from the customer, I guess.

2023-08-11 23:10 UTC, wendycwong commented
Veronika:  I ran the notebook with the customer data and it worked.  Thanks, Wendy

2023-08-11 23:10 UTC, wendycwong approved these changes

2023-08-14 07:39 UTC, merged