[GH-15851] Bring 3.44 release blog to user guide
h2oai/h2o-3 pull request #15882
Opened 2023-10-26 14:32 UTC by hannah-tillman

#15851 

This PR replaces the 3.42 release blog w/ the 3.44 release blog and brings in the tagged examples into each section. I also updated the link to the prior releases.

2023-10-26 14:52 UTC, mn-mikke approved these changes
LGTM, thank you!

2023-10-31 23:27 UTC, wendycwong requested changes

2023-10-31 23:27 UTC, wendycwong commented on h2o-docs/src/product/blog-releases.rst
> +We are excited to announce the release of H2O-3 3.44.0.1! We have added and improved many items. A few of our highlights are the implementation of AdaBoost, Shapley values support, Python 3.10 and 3.
Please add

GLM

to the list of algorithms that support custom metrics.

2023-11-03 16:24 UTC, wendycwong approved these changes

2023-11-03 16:25 UTC, merged