[DOCS] Craft GAM Examples
h2oai/h2o-3 pull request #15945
Opened 2023-11-22 08:01 UTC by shaunyogeshwaran

Crafted new examples for the GAM algorithm to showcase the different parameters.

2023-12-05 01:19 UTC, wendycwong commented
@shaunyogeshwaran : Thank you for working on this.  However, I don't think we need an example for every parameters for GAM.  In fact, I think the only parameters you want to showcase are those specific to GAM.  What do you think?

2024-01-02 13:14 UTC, hannah-tillman commented
@shaunyogeshwaran please change the target branch to rel-3.44.0

2024-01-05 14:47 UTC, hannah-tillman commented
Are those examples marked as *doesn't run*/*does not run* still broken?

2024-01-15 13:20 UTC, hannah-tillman approved these changes

2024-02-08 23:07 UTC, wendycwong requested changes
Driving home now.  Will review the latter part soon.  Thanks for all the good work.

2024-02-08 23:07 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +""",
Please replace lines 307 to 330 with:

>>> import h2o
 >>> from h2o.estimators.gam import H2OGeneralizedAdditiveEstimator
 >>> h2o.init()
 >>> h2o_data = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/glm_test/multinomial_10_classes_10_cols_10000_Rows_train.csv")
 >>> h2o_data["C11"] = h2o_data["C11"].asfactor()
 >>>  y="C11"
 >>> x = ["C9","C10"]
 >>> h2o_model = H2OGeneralizedAdditiveEstimator(family='multinomial', store_knot_locations=True, gam_columns=["C6","C7","C8”], num_knots=[3,4,5])
 >>> h2o_model.train(x=x, y=y, training_frame=h2o_data)
 >>> h2o_model.get_knot_locations()

2024-02-08 23:07 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +""",
Please remove 332 to 357 as this is a GLM parameter and should have been illustrated there.

2024-02-09 03:41 UTC, wendycwong requested changes
Please do a git pull before you make changes.  I pushed a fix for a parameter from

store_knot_location to store_knot_locations

Thanks.

2024-02-09 03:41 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +""",
Replace lines 387 to 411 with:

>>> import h2o
 >>> from h2o.estimators.gam import H2OGeneralizedAdditiveEstimator
 >>> h2o.init()
 >>> h2o_data = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/glm_test/binomial_20_cols_10KRows.csv")
 >>>  y="C21"
 >>> x = ["C19","C20"]
 >>> h2o_model = H2OGeneralizedAdditiveEstimator(family=‘gaussian’, gam_columns=["C16","C17","C18”], bs=[2,2,2], splines_non_negative=[True, True, True]))
 >>> h2o_model.train(x=x, y=y, training_frame=h2o_data)
 >>> h2o_model.coef()

2024-02-09 03:41 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +""",
Please replace lines 414 to 438 with

>>> import h2o
 >>> from h2o.estimators.gam import H2OGeneralizedAdditiveEstimator
 >>> h2o.init()
 >>> h2o_data = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/glm_test/binomial_20_cols_10KRows.csv")
 >>>  y="C21"
 >>> x = ["C19","C20"]
 >>> h2o_model = H2OGeneralizedAdditiveEstimator(family=‘gaussian’, gam_columns=["C16","C17","C18”], bs=[2,2,2], spline_orders=[3,4,5])
 >>> h2o_model.train(x=x, y=y, training_frame=h2o_data)
 >>> h2o_model.coef()

2024-02-09 03:41 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +""",
Please replace lines 441 to 465 with:

>>> import h2o
 >>> from h2o.estimators.gam import H2OGeneralizedAdditiveEstimator
 >>> h2o.init()
 >>> h2o_data = h2o.import_file("https://s3.amazonaws.com/h2o-public-test-data/smalldata/glm_test/binomial_20_cols_10KRows.csv")
 >>>  y="C21"
 >>> x = ["C19","C20"]
 >>> h2o_model = H2OGeneralizedAdditiveEstimator(family=‘gaussian’, gam_columns=["C16","C17","C18”], bs=[1,1,1], standardize_tp_gam_cols=True)
 >>> h2o_model.train(x=x, y=y, training_frame=h2o_data)
 >>> h2o_model.coef()

2024-02-09 03:41 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +""",
please delete lines 467 to 520 because startval is more a GLM model thing.

2024-02-09 03:41 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_gam.py
> +)
Please delete lines 521-574 as those are again GLM parameters.

2024-02-21 18:52 UTC, hannah-tillman approved these changes

2024-02-28 17:39 UTC, wendycwong approved these changes

2024-03-01 03:22 UTC, merged