Anova GLM Examples.
h2oai/h2o-3 pull request #15943
Opened 2023-11-22 07:54 UTC by shaunyogeshwaran

Crafted new examples to showcase the different parameters.

2023-12-05 01:21 UTC, wendycwong commented
@shaunyogeshwaran : Thank you for working on this. However, I don't think we need an example for every parameters for ANOVAGLM. In fact, I think the only parameters you want to showcase are those specific to ANOVAGLM. What do you think?

2023-12-05 08:07 UTC, shaunyogeshwaran commented
> What do you think?

I agree @wendycwong. I think crafting examples for each and every parameter makes the docs look tedious. I will go ahead and make the necessary changes to the other algorithms to only include what's unique to that algorithm.

2024-01-12 13:43 UTC, hannah-tillman submitted a review, later dismissed

2024-01-18 17:18 UTC, hannah-tillman approved these changes

2024-01-22 21:15 UTC, wendycwong requested changes

2024-01-22 21:15 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_anovaglm.py
> +    prior="""
Remove lines 88 to 101.  I will remove this parameter.

2024-01-22 21:15 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_anovaglm.py
> +    save_transformed_framekeys="""
Remove lines 102 to 115.  The parameter prior is not specific to anovaglm.

2024-01-22 21:15 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_anovaglm.py
> +>>> import h2o
remove lines 130 to 157, tweedie_link_power and tweedie_variance_power are not ANOVAGLM specific parameters.  They should be made into examples in GLM and not here.

2024-01-22 21:15 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_anovaglm.py
> +""",
change lines 117 to 128 with

>>> import h2o
 >>> h2o.init()
 >>> from h2o.estimators import H2OANOVAGLMEstimator 
 >>> train = h2o.import_file("http://s3.amazonaws.com/h2o-public-test-data/smalldata/prostate/prostate_complete.csv.zip")
 >>> x = ['AGE', 'VOL', 'DCAPS']
 >>> y = 'CAPSULE'
 >>> anova_model = H2OANOVAGLMEstimator(family='binomial',
 ...                                    lambda_=0,
 ...                                    missing_values_handling="skip",
 ...                                    save_transformed_framekeys=False)  
 >>> anova_model.train(x=x, y=y, training_frame=train)
 >>>  transformFrame = h2o.get_frame(anova_model._model_json['output']['transformed_columns_key']['name'])
 >>> print(transformFrame)

2024-01-24 20:58 UTC, wendycwong submitted a review, later dismissed

2024-01-26 10:59 UTC, hannah-tillman approved these changes

2024-02-29 13:38 UTC, merged