[DOCS] Craft RuleFit Examples
h2oai/h2o-3 pull request #15984
Opened 2023-12-22 08:36 UTC by shaunyogeshwaran

Crafted new examples for the RuleFit algorithm to showcase the different parameters.

2024-01-12 13:42 UTC, hannah-tillman approved these changes

2024-01-18 17:07 UTC, hannah-tillman approved these changes

2024-02-29 13:12 UTC, hannah-tillman approved these changes

2024-03-01 19:48 UTC, hannah-tillman approved these changes

2024-03-04 21:44 UTC, wendycwong requested changes

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> train, test = df.split_frame(ratios=[0.8], seed=1)
Remove line 64: >>> train, test = df.split_frame(ratios=[0.8], seed=1)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> rfit.train(training_frame=train, x=x, y=y)
change
>>> rfit.train(training_frame=train, x=x, y=y)
to
>>> rfit.train(training_frame=df, x=x, y=y)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> rfit.predict(test)
remove line rfit.predict(test)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> train, test = df.split_frame(ratios=[0.8], seed=1)
remove line: >>> train, test = df.split_frame(ratios=[0.8], seed=1)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> rfit.train(training_frame=train, x=x, y=y)
change

rfit.train(training_frame=train, x=x, y=y)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> rfit.predict(test)
remove >>> rfit.predict(test)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> train, test = df.split_frame(ratios=[0.8], seed=1)
remove line with >>> train, test = df.split_frame(ratios=[0.8], seed=1)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> rfit.train(training_frame=train, x=x, y=y)
change
>>> rfit.train(training_frame=train, x=x, y=y)
to
>>> rfit.train(training_frame=df, x=x, y=y)

2024-03-04 21:44 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +>>> rfit.predict(test)
remove >>> rfit.predict(test)

2024-03-05 13:54 UTC, valenad1 requested changes
I agree with wendy, I would also use different values than the default in the examples.

2024-03-06 10:38 UTC, maurever requested changes
Why did you add examples only to the `max_categorical_levels`,` algorithm`, and `max_num_rules` parameters?

It would be nice to add examples also for:
- min_rule_lenght
- max_rule_length
- model_type
- distribution
- rule_generation_ntrees
- rule_importance
- predict_rules

2024-03-06 17:35 UTC, wendycwong commented
Good call Veronika, I missed those rulefit specific parameters.

2024-03-20 06:31 UTC, shaunyogeshwaran commented
@maurever What would some values for `rule_importance` and ` predict_rules` be? The docs don't give much info

2024-04-26 13:12 UTC, valenad1 commented
> @maurever What would some values for `rule_importance` and ` predict_rules` be? The docs don't give much info

`rule_importance` is just output. So train the model and call `model.rule_importance` and same for `predict_rules`. E.g [here](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/rulefit.html?highlight=rulefit#examples).

2024-04-29 11:47 UTC, maurever commented
Thanks, @valenad1, you are correct. It is my mistake to conclude them in the list of parameters. If I am correct, we can also add examples of how to use these functions. WDYT, @shaunyogeshwaran ?

2024-04-30 08:35 UTC, shaunyogeshwaran commented
> If I am correct, we can also add examples of how to use these functions. WDYT, @shaunyogeshwaran ?

Agreed, that is something I will be able to look into. @hannah-tillman what are your thoughts on this?

2024-04-30 12:06 UTC, hannah-tillman commented
> Agreed, that is something I will be able to look into. @hannah-tillman what are your thoughts on this?

@shaunyogeshwaran Yeah adding those examples in won't be an issue. Both of those calls are in written out in the gen_rulefit.py page so instead of adding them to the bottom of the examples list you'll just add them to their respective sections like this under ``:return:``

```
:examples:
>>> example content
>>> example content
>>> etc
"""
```

2024-06-07 22:18 UTC, wendycwong requested changes

2024-06-07 22:18 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +...                            max_num_rules=-2,
please set

max_num_rules = 3 

or some positive number

2024-06-07 22:18 UTC, wendycwong commented on h2o-bindings/bin/custom/python/gen_rulefit.py
> +    predict_rules="""
Please add how you will use 

predict_rules.

2024-09-26 18:08 UTC, wendycwong requested changes

2024-10-01 13:48 UTC, hannah-tillman submitted a review, later dismissed

2024-10-09 21:43 UTC, wendycwong commented
Jenkins still cannot run.  Please change github branch name and remove the #.

2024-10-14 04:33 UTC, closed without merging