[DOCS] Craft DT Example
h2oai/h2o-3 pull request #15998
Opened 2024-01-03 06:38 UTC by shaunyogeshwaran

Crafted new examples for the DT algorithm to showcase the different parameters.

2024-01-12 13:52 UTC, hannah-tillman approved these changes

2024-01-18 16:49 UTC, hannah-tillman submitted a review, later dismissed

2024-03-05 13:43 UTC, valenad1 commented on h2o-py/h2o/estimators/decision_tree.py
> +        >>> target_variable = 'CAPSULE'
Add some constant values.

prostate["const_1"] = 6

2024-03-05 13:46 UTC, valenad1 commented on h2o-py/h2o/estimators/decision_tree.py
> +        >>> target_variable = 'CAPSULE'
Define also `RACE` as categorical and use different encoding than default.

2024-03-05 13:46 UTC, valenad1 commented on h2o-py/h2o/estimators/decision_tree.py
>          "sort_by_response", "enum_limited"]``, defaults to ``"auto"``.
Out of scope but I would mention that `auto` means `enum`.

2024-03-05 13:48 UTC, valenad1 commented on h2o-py/h2o/estimators/decision_tree.py
> +        ...                                    min_rows=10)
Use different number than default.

2024-03-05 13:51 UTC, valenad1 requested changes
One example is not working and I would use different number than default.

Otherwise, LGTM, Thank you!

2024-05-21 11:50 UTC, hannah-tillman approved these changes

2024-06-07 22:01 UTC, wendycwong approved these changes

2024-06-10 13:10 UTC, shaunyogeshwaran commented
Hello @valenad1, I've made the requested changes 👍

2024-08-14 15:54 UTC, valenad1 approved these changes
Works for me. Thank you @shaunyogeshwaran

2024-08-23 03:03 UTC, merged