GH- Improve custom metric doc
h2oai/h2o-3 pull request #16075
Opened 2024-02-16 09:50 UTC by maurever

Issue: https://github.com/h2oai/h2o-3/issues/15960

2024-03-25 17:29 UTC, wendycwong requested changes

2024-03-27 12:03 UTC, maurever commented on h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
> +    - ``pred``: a double array storing the model prediction output.  For regresion problems, the prediction value is stored in ``pred[0]``; for classification problems, the prediction value for class
Thanks. Good catch! :)

2024-03-27 12:04 UTC, maurever commented on h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
> +- :math:`\sqrt{}` is done in value function from results from ``reduce`` phase
Not in postGlobal, but in the 'metric' function. Thanks @wendycwong for catch this.

2024-03-27 13:45 UTC, maurever commented on h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
> +- :math:`\sqrt{}` is done in value function from results from ``reduce`` phase
I think I improved the text to be more precious. Am I right now,  @wendycwong?

2024-04-01 20:16 UTC, wendycwong submitted a review, later dismissed
Veronika:

Thank you for taking care of this one.  Just one minor change request.


Wendy

2024-04-02 15:49 UTC, wendycwong commented on h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
> +- :math:`\sqrt{}` is done in value function from results from ``reduce`` phase
Yes and thank you

2024-04-10 13:22 UTC, maurever commented on h2o-docs/src/product/data-science/algo-params/custom_metric_func.rst
> +    - ``pred``: a double array storing the model prediction output.  For regresion problems, the prediction value is stored in ``pred[0]``; for classification problems, the prediction value for class
Thanks @wendycwong!

2024-04-10 14:03 UTC, wendycwong approved these changes

2024-04-11 07:25 UTC, merged