GH-18186: Updating user guide pages for Cloud Integration to reflect makersaurus guidelines
h2oai/h2o-3 pull request #16187
Opened 2024-05-02 14:32 UTC by hannah-tillman

#16186 

This PR updates the cloud integration pages to adhere to the style guide.

Question: I was testing out all the links and found that the ones for the IBM Data Science Experience page kept 404-ing. I tried to find it by searching IBM and couldn't. Any idea on if that still exists?

2024-05-23 00:40 UTC, wendycwong requested changes

2024-06-05 16:20 UTC, hannah-tillman commented on h2o-docs/src/product/cloud-integration/kubernetes.rst
> +  Official K8s images don’t apply any `security settings <../security.html>`__. The default user is ``root``. If you require a secure interface with H2O running the image, you need to change the user
I tested this link again and it is the one that is currently live, so I am confused why these links aren't working for you

2026-01-22 09:27 UTC, shaunyogeshwaran approved these changes
LGTM

2026-05-04 06:17 UTC, shaunyogeshwaran commented
Closing in favor of #16841, which is the active PR for #16186.

2026-05-04 06:17 UTC, closed without merging