GH-16425 Add JDBC parameter validation [nocheck]
h2oai/h2o-3 pull request #16432
Opened 2024-10-22 19:55 UTC by krasinski

fixes #16425

2024-10-22 20:08 UTC, wendycwong submitted a review, later dismissed

2024-10-23 11:46 UTC, valenad1 requested changes
It should go to the rel-3.46.0 I suppose

2024-10-23 15:41 UTC, wendycwong commented
@valenad1 :  If I remember correctly, this is the second time you remind the team to use rel-3.46.0 and not the master branch.  LOL.

2024-10-23 15:41 UTC, wendycwong approved these changes

2024-10-23 15:51 UTC, valenad1 commented
It happens, make sense sometime to merge it to master first and cherry-pick to rel-* later, but I want to be sure, it is this purpose or mistake :)

2024-10-23 15:52 UTC, valenad1 approved these changes
lgtm, thank you!

2024-10-25 16:14 UTC, wendycwong approved these changes

2024-10-27 16:13 UTC, merged