PUBDEV-7720 rfit tests and docs adjustments
h2oai/h2o-3 pull request #4934
Opened 2020-09-19 19:21 UTC by koniecsveta

2020-09-22 04:56 UTC, ledell commented
I have another PR over here covering some related RuleFit user guide pages... I put it into rel-zeno since that's where the original PR went. https://github.com/h2oai/h2o-3/pull/4943

2020-09-22 05:30 UTC, ledell requested changes
I made a few commit suggestions for R style guide alignment.  I am also wondering if you can update the example in the Rdocs (created in `gen_rulefit.py`) to use the example here (I made some edits to the user guide rst file): https://github.com/h2oai/h2o-3/blob/7268ddecf200cd11f73cb743efd93ca50089fd28/h2o-docs/src/product/data-science/rulefit.rst#examples

2020-09-22 05:30 UTC, ledell commented on h2o-bindings/bin/custom/R/gen_rulefit.py
> +rfit = h2o.rulefit(y=response, x=predictors, training_frame = titanic, max_rule_length=10,
```suggestion
rfit <- h2o.rulefit(y = response, x = predictors, training_frame = titanic, max_rule_length = 10, 
```

2020-09-22 05:30 UTC, ledell commented on h2o-bindings/bin/custom/R/gen_rulefit.py
>  max_num_rules=100, seed=1234, model_type="rules")
```suggestion
max_num_rules = 100, seed = 1, model_type = "rules")
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
> +    rf_h2o = h2o.rulefit(y=response, x=predictors, training_frame = train, max_rule_length=10, max_num_rules=100, seed=1234, model_type="rules")
```suggestion
    rfit <- h2o.rulefit(y = response, x = predictors, training_frame = train, max_rule_length = 10, max_num_rules = 100, seed = 1, model_type="rules")
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
> +    print(rf_h2o@model$rule_importance)
```suggestion
    print(rfit@model$rule_importance)
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
> +    h2o.predict(rf_h2o, newdata=test)
```suggestion
    h2o.predict(rfit, newdata = test)
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
> +    expect_that(h2o.auc(h2o.performance(rf_h2o)), equals(h2o.auc(h2o.performance(rf_h2o, newdata =  test))))
```suggestion
    expect_that(h2o.auc(h2o.performance(rfit)), equals(h2o.auc(h2o.performance(rfit, newdata =  test))))
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/tests/testdir_algos/rulefit/runit_rulefit_titanic.R
> +    expect_that(h2o.logloss(h2o.performance(rf_h2o)), equals(h2o.logloss(h2o.performance(rf_h2o, newdata =  test))))
```suggestion
    expect_that(h2o.logloss(h2o.performance(rfit)), equals(h2o.logloss(h2o.performance(rfit, newdata =  test))))
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/h2o-package/R/rulefit.R
> +#' rfit = h2o.rulefit(y=response, x=predictors, training_frame = titanic, max_rule_length=10,
```suggestion
#' rfit <- h2o.rulefit(y = response, x = predictors, training_frame = titanic, max_rule_length = 10, 
```

2020-09-22 05:30 UTC, ledell commented on h2o-r/h2o-package/R/rulefit.R
>  #' max_num_rules=100, seed=1234, model_type="rules")
```suggestion
#' max_num_rules = 100, seed=1, model_type = "rules")
```

2020-09-22 12:02 UTC, koniecsveta commented
> I made a few commit suggestions for R style guide alignment. I am also wondering if you can update the example in the Rdocs (created in `gen_rulefit.py`) to use the example here for consistency -- there are a few slight changes (I made some edits to the user guide rst file): https://github.com/h2oai/h2o-3/blob/7268ddecf200cd11f73cb743efd93ca50089fd28/h2o-docs/src/product/data-science/rulefit.rst#examples


3cf6c7a

2020-09-23 02:49 UTC, ledell approved these changes
This is great, thanks!

2020-09-25 09:24 UTC, koniecsveta commented
added do not merge as tests are failing / need to investigate why

2020-09-29 06:40 UTC, merged