PUBDEV-7945: Docs: Add that AUCPR can now be plotted
h2oai/h2o-3 pull request #5208
Opened 2020-12-30 16:28 UTC by hannah-tillman

For: https://h2oai.atlassian.net/browse/PUBDEV-7945

Added the AUCPR plot section to the performance & prediction section of the user guide (under ROC curve). Please let me know if you want anything updated!

2020-12-30 18:23 UTC, neemah2o requested changes
Correct the typo for "sensative" to "sensitive". Otherwise, it looks good.

2020-12-30 18:23 UTC, neemah2o commented on h2o-docs/src/product/performance-and-prediction.rst
> +The area under the precision-recall curve graph represents how well a binary classification model is able to distinguish between precision recall pairs or points. The AUCPR does not care about True N
typo, "sensitive" not "sensative"

2021-01-01 17:09 UTC, maurever approved these changes
Looks good, thanks @hannah-tillman !

2021-01-04 08:45 UTC, neemah2o approved these changes

2021-01-04 13:36 UTC, merged