PUBDEV-8091 nicer api for baseline hazard and survival
h2oai/h2o-3 pull request #5424
Opened 2021-04-08 12:15 UTC by satai

2021-04-08 12:26 UTC, satai commented
Does this one look OK to you, @grigory93 ?

2021-04-08 13:13 UTC, grigory93 approved these changes
thanks!

2021-04-08 13:15 UTC, grigory93 commented
documentation question - do new accessors get documented automatically?
we should have our Cox PH documentation example(s) expanded with new functionality too...

2021-04-08 13:30 UTC, michalkurka commented
@satai thank you - LGTM - but please rebase on top of rel-zipf and change the base branch

2021-04-08 14:05 UTC, satai commented
> @satai thank you - LGTM - but please rebase on top of rel-zipf and change the base branch

Zipfed, @michalkurka

2021-04-08 15:50 UTC, michalkurka requested changes
@satai you are changing generated classes, the change needs to be made in the helpers that the generator uses

take a look at eg. gen_aggregator.py and method class_extensions: https://github.com/h2oai/h2o-3/blob/master/h2o-bindings/bin/custom/python/gen_aggregator.py#L4

2021-04-08 15:52 UTC, michalkurka commented on h2o-py/h2o/estimators/coxph.py
> +import h2o
you don't need this import if you use H2OFrame.get_frame

2021-04-08 15:54 UTC, michalkurka commented
@hannah-tillman please be aware of this PR when working on PUBDEV-8091

2021-04-08 16:16 UTC, michalkurka commented
@satai @grigory93 I fixed the issues, change the naming to conform to h2o conventions, please take a look

2021-04-09 18:16 UTC, michalkurka approved these changes

2021-04-09 18:16 UTC, merged