PUBDEV-8558: Example of combining multiple POJOs + feature engineering
h2oai/h2o-3 pull request #6051
Opened 2022-01-28 19:28 UTC by michalkurka

2022-01-30 22:05 UTC, neemah2o requested changes
Looks good other than add info on %s() , line 84

2022-01-31 20:41 UTC, michalkurka commented on h2o-py/tests/testdir_generic_model/pyunit_pojo_import.py
> +    public %s() {
thanks, will add documentation to the methods. This is a constructor that initializes the class and all the inner fields.

2022-01-31 21:11 UTC, michalkurka commented
@neemah2o please take another, look - is it clearer now?

2022-02-01 06:49 UTC, neemah2o commented
Yes, it's more clear now

2022-02-01 06:49 UTC, neemah2o approved these changes

2022-02-01 14:53 UTC, merged