PUBDEV-8585: enable alternate p value calculation as in sklearn
h2oai/h2o-3 pull request #6096
Opened 2022-03-10 23:09 UTC by wendycwong

This PR completes the task in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8585

I checked the covariance matrix calculation as in https://stats.stackexchange.com/questions/89484/how-to-compute-the-standard-errors-of-a-logistic-regressions-coefficients and found that we have implemented the same calculation in our p-value calculation.

To prove that I added a java test to manually calculate the covariance matrix, the standard error, the z-value and then the p-value.  I then compared this calculation with the on in the GLM code and they match well.  I even use a different method to perform the equivalent of finding the inverse of the covariance matrix.

Hence, I am at a loss as to why the p-values of binomial backward elimination yield different values then the one from our customer.  Whatever is causing the difference, it is not the p-value calculation.  It is the other things that are happening as the binomial uses iterative update.

2022-04-09 03:07 UTC, wendycwong commented
Benchmark results:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/7231712/162554123-3f7e4abc-0ada-41e4-83a7-bbb57659e5d5.png">

2022-04-09 03:08 UTC, wendycwong commented
Really should be no difference in result because compute_p_values is not enabled.

2022-04-10 23:13 UTC, ledell requested changes
Hi @wendycwong just some small feedback on the param descriptions.  Can you specify explicitly what a default of `-1` means?  (e.g. disabled, or something else)

2022-04-10 23:14 UTC, ledell commented on h2o-py/h2o/estimators/model_selection.py
> +                 objective_epsilon=-1.0,  # type: float
These should be -1 not -1.0.

2022-04-10 23:16 UTC, ledell commented
@wendycwong My requested changes are minor (not blockers) so if you want this to go into 3.36.1.1 w/o the changes, that's ok with me (can easily follow-up later).

2022-04-10 23:19 UTC, ledell approved these changes
Approving so you can merge if you need to on Monday (see my notes above about improving param descriptions and -1.0 default value on Python client.

2022-04-11 17:57 UTC, wendycwong commented on h2o-py/h2o/estimators/model_selection.py
> +                 objective_epsilon=-1.0,  # type: float
yes, they are of type double.

2022-04-12 11:59 UTC, merged