PUBDEV-8691 Standard Decision Tree implementation
h2oai/h2o-3 pull request #6182
Opened 2022-04-28 11:48 UTC by syzonyuliia

https://h2oai.atlassian.net/browse/PUBDEV-8691

2022-05-16 13:57 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/SDT.java
> +    private int maxDepth;
We have a project style with leading underscore for Class field naming. So _maxDepth here.

Since its everywhere, we have to follow this style

2022-06-26 11:09 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/CompressedSDT.java
> +    public double[][] nodes;
Can we have structure of the array documented here?

2022-06-26 16:23 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/SDT.java
> +    private int log2(int value) {
MathUtils.log2

2022-06-27 09:27 UTC, valenad1 commented
Can you please remove (store it somewhere else) the unused code and sysouts replace with Log?

2022-06-28 12:22 UTC, valenad1 commented
Can we have a small tests for all the MR tasks we are using? Eg. that histogram for 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 of equal width 2 gives  1 2; 3 4; 5 6; 7, 8; 9 10. We have to be sure that all the small parts of codes give the expected results

2022-07-25 13:32 UTC, valenad1 requested changes

2022-07-25 15:34 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/binning/Histogram.java
> +                ? Stream.generate(() -> new double[]{(-1) * Double.MAX_VALUE, Double.MAX_VALUE})
Plese document why not Double.MIN_VALUE

2022-07-25 15:37 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/SDT.java
> +        for (int featureIndex = 0; featureIndex < featuresNumber; featureIndex++) {
Discuss the parallelization possibilities here

2022-07-25 15:38 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/SDT.java
> +    public final static double EPSILON = 0.000001d;
Reasoning behind this value?

2022-07-26 13:27 UTC, valenad1 commented
Please test that API is working with some smoke test for python and R

2022-07-26 13:46 UTC, valenad1 commented on h2o-algos/src/main/java/hex/tree/sdt/SDT.java
> +        // todo - add limit by information gain (at least because of ideal split for example 11111)
I think its similar to DRF attribute min_split_improvement.

2022-12-09 15:26 UTC, syzonyuliia commented
Closed, the new pull request was created - https://github.com/h2oai/h2o-3/pull/6447

2022-12-09 15:26 UTC, closed without merging