PUBDEV-8681 GAM predict failure with fold_column
h2oai/h2o-3 pull request #6185
Opened 2022-04-30 01:43 UTC by wendycwong

This PR fixes the bug in JIRA: https://h2oai.atlassian.net/browse/PUBDEV-8681.

There is a bug in my code where the fold column is mistreated as a normal column to score for. 

I added code to make sure the fold column is treated properly.

However, this will cause the fold column to be deleted from the dataset completely and I do not know why that is.  I have spotted where the fold column is deleted in the code.  It is in ModelBuilder.java in line 264.

2022-05-19 14:14 UTC, michalkurka commented on h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8681_paul_gam_cv_no_cv.R
> +    browser()
probably just forgotten

2022-05-19 14:16 UTC, michalkurka commented on h2o-core/src/main/java/hex/ModelBuilder.java
> +        if (!_parms._is_cv_model && _parms._fold_column != null) {
I think this really should not be on ModelBuilder - I will request changes based on these lines.

We can think of better solution together.

2022-05-19 14:16 UTC, michalkurka commented on h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
> +import com.google.gson.internal.Streams;
looks unused

2022-05-19 14:17 UTC, michalkurka requested changes
Requesting changes due to specific handling of fold column in ModelBuilder - see inline comments

2022-06-22 20:58 UTC, wendycwong commented on h2o-r/tests/testdir_algos/gam/runit_PUBDEV_8681_paul_gam_cv_no_cv.R
> +    browser()
Sorry.  Fixed.

2022-06-22 20:59 UTC, wendycwong commented on h2o-algos/src/main/java/hex/gam/MatrixFrameUtils/GamUtils.java
> +import com.google.gson.internal.Streams;
I removed all unused code.  I hope.

2022-06-23 15:43 UTC, michalkurka approved these changes
LGTM, thank you @wendycwong

2022-06-25 19:50 UTC, merged