PUBDEV-8442: Readability update for Python docs
h2oai/h2o-3 pull request #6195
Opened 2022-05-16 15:32 UTC by hannah-tillman

For: [PUBDEV-8442](https://h2oai.atlassian.net/browse/PUBDEV-8442)

This ticket was originally going to just be making proper lists where there was just paragraph listing, but I did a scan through the entire Python module docs to update readability. Please let me know if anything should be changed.

2022-05-17 20:31 UTC, zainhaq-h2o approved these changes
I left a few minor suggestions, but LGTM otherwise - thanks Hannah!

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/backend/server.py
>      terminate it is to kill the java process from the terminal.
```suggestion
    terminate it is to end the Java process from the terminal.
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/explanation/_explain.py
>      PDP assumes independence between the feature for which is the PDP computed and the rest.
This sentence is a bit confusing. It might be worthwhile to try improving it

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/explanation/_explain.py
> +    :param centered: a bool whether to center curves around 0 at the first valid x value or not.
```suggestion
    :param centered: a bool that determines whether to center curves around 0 at the first valid x value.
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/explanation/_explain.py
> +    :param output_graphing_data: a bool whether to output final graphing data to a frame.
```suggestion
    :param output_graphing_data: a bool that determines whether to output final graphing data to a frame.
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/explanation/_explain.py
>      lines of residuals, that is just an indication that your response variable was integer
```suggestion
    lines of residuals, that is just an indication that your response variable was
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/explanation/_explain.py
>      valued instead of real valued.
```suggestion
    integer-valued instead of real-valued.
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/frame.py
> +        Create a new H2OFrame equal to elementwise logarithm of the gamma function of the current frame.
```suggestion
        Create a new H2OFrame equal to element-wise logarithm of the gamma function of the current frame.
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/model/binomial.py
> +        Retrieves the Kolmogorov-Smirnov metric for a given binomial model. The number returned is in range between 0 and 1.
```suggestion
        Retrieves the Kolmogorov-Smirnov metric (K-S metric) for a given binomial model. The number returned is in range between 0 and 1.
```

2022-05-17 20:31 UTC, zainhaq-h2o commented on h2o-py/h2o/model/metrics_base.py
>          :param server: if True, generate plot inline using matplotlib's "Agg" backend.
```suggestion
        :param server: if True, generate plot inline using matplotlib's Anti-Grain Geometry (AGG) backend.
```

2022-05-18 13:10 UTC, sebhrusen requested changes
Thanks for this effort @hannah-tillman

I'd like to ask you if you have any idea how we can ensure proper doc formatting in Py and R, given that we (devs) will keep adding lousily formatted doc :)
I'd suggest the following:
- come up with a list of best practices for doc formatting (e.g. Py keywords or functions wrapped in double backticks [``foo``])
- ask everyone to add you to every PR containing significant doc changes so that you can review that part.

would you be ok for that?

2022-05-18 13:25 UTC, hannah-tillman commented
@sebhrusen I would LOVE if everyone tagged me for review with docs updates! Absolutely yes to that.

And I will start working on a best practices! We've bounced that task around in the team before, but it keeps falling through with team changes and general busy-ness. Would be nice to have a basic standardized set of rules for everyone to look to :)

2022-05-18 14:31 UTC, sebhrusen commented
@hannah-tillman ok, great! Yes, a few basic rules would be helpful to everyone.

for the reviews, that's the most difficult to enforce I guess: we 'll probably have to remind the team on Slack once in a while, and otherwise it's our responsibility to invite you for review each time we create a PR with doc changes or review someone else's PR.

2022-05-23 19:20 UTC, merged