PUBDEV-8829: Adding VIF to GLM docs
h2oai/h2o-3 pull request #6314
Opened 2022-09-12 17:39 UTC by hannah-tillman

For: [PUBDEV-8829](https://h2oai.atlassian.net/browse/PUBDEV-8829)

This pr adds the VIF information to the GLM docs. Please let me know if anything needs to be updated.

2022-09-12 17:59 UTC, michalkurka approved these changes

2022-09-12 23:40 UTC, wendycwong requested changes

2022-09-12 23:40 UTC, wendycwong commented on h2o-docs/src/product/data-science/glm.rst
> +- building a GLM regression model,
except for *x* should be except for *y*

2022-09-13 21:28 UTC, wendycwong approved these changes

2022-09-13 22:33 UTC, merged