PUBDEV-8461: Restructuring algorithm parameters and grid search hyperparameters
h2oai/h2o-3 pull request #6422
Opened 2022-11-11 19:02 UTC by hannah-tillman

This is the draft PR for the new restructuring of the algorithm parameters.

What I need in the initial review:

- [ ] are the algorithm-specific parameters correct for each algorithm
- [ ] does it make sense to have the sub-groups for:
        - [ ] GLM Family parameters (i.e., shared parameters for GLM, GAM, MS, & ANOVA)
        - [ ] Tree algorithm parameters (i.e., shared parameters for GBM, DRF, XGBoost, Isolation Forest, Ex. Isolation Forest)
- [ ] are the hyperparameter lists on the grid search page correct
        - [ ] does it make sense to have the shared tables for:
                 - [ ] common hyperparameters for supervised algos
                 - [ ] common hyperparameters for unsupervised algos
                 - [ ] shared tree algorithm hyperparameters
                 - [ ] shared GLM family hyperparameters

Let me know if you need help building the docs to look through them easier or if anything doesn't make sense!

2022-11-16 21:15 UTC, wendycwong commented on h2o-docs/src/product/data-science/anova_glm.rst
> +''''''''''''''''''''''''
The following parameters are specific to GLM, GAM, Modelselection, ANOVAGLM.  So not sure how you want to call them.

2022-11-17 00:02 UTC, wendycwong requested changes

2022-11-18 20:53 UTC, hannah-tillman commented on h2o-docs/src/product/data-science/gam.rst
> +GLM family parameters
@wendycwong Thoughts on something like this? Having a link on GAM, MS, and ANOVA linking to a shared parameter section on the GLM page where each section is laid out?

https://user-images.githubusercontent.com/52463461/202790160-dfeeb738-58a5-421c-bdc0-f95ee33dd656.mov

2022-11-18 20:53 UTC, hannah-tillman commented on h2o-docs/src/product/data-science/gam.rst
> +GLM family parameters
Or maybe something more like this with small icons for which algos share the parameter:
![Screen Shot 2022-11-18 at 2 47 39 PM](https://user-images.githubusercontent.com/52463461/202800079-41d700cc-a764-4d92-93d3-6a5ad0a24d13.png)

2022-11-23 11:24 UTC, haohenggang commented
@wendycwong @vindows @honzasterba @pkozelka

2022-11-23 11:29 UTC, haohenggang commented
@wendycwong @vindows @honzasterba @pkozelka Could you please share me if there is  any examples of using random forests algorithm by java or Android environment？

2022-12-09 19:32 UTC, wendycwong commented on h2o-docs/src/product/data-science/gam.rst
> +GLM family parameters
Yes, this looks very nice indeed!

2022-12-13 00:22 UTC, wendycwong commented
@haohenggang Here is a code snippet on how to use random forest:

            Frame fr = Scope.track(parseTestFile("smalldata/junit/titanic_alt.csv"));
            DRFModel.DRFParameters parms = new DRFModel.DRFParameters();
            parms._train = fr._key;
            parms._distribution = gaussian;
            parms._response_column = "age";
            parms._ntrees = 5;
            parms._max_depth = 4;
            parms._min_rows = 1;
            parms._nbins = 50;
            parms._score_each_iteration = true;
            parms._seed = 42;

            DRF job = new DRF(parms);
            DRFModel drf = job.trainModel().get();

2023-04-27 19:19 UTC, hannah-tillman commented
Resolved in subtasks PUBDEV-9051 through PUBDEV-9071. Part of 3.40.0.4 release.

2023-04-27 19:19 UTC, closed without merging